export const USERS_REQUEST = 'USERS_REQUEST';
export const USERS_RESOLVE = 'USERS_RESOLVE';
export const USERS_REJECT  = 'USERS_REJECT';

export const CREATE_USERS_RESOLVE = 'CREATE_USERS_RESOLVE';
export const CREATE_USERS_REJECT  = 'CREATE_USERS_REJECT';

export const UPDATE_USERS_RESOLVE = 'UPDATE_USERS_RESOLVE';
export const UPDATE_USERS_REJECT  = 'UPDATE_USERS_REJECT';

export const REMOVE_USERS_RESOLVE = 'REMOVE_USERS_RESOLVE';
export const REMOVE_USERS_REJECT  = 'REMOVE_USERS_REJECT';